### ISSUE TITLE
Category navigation settings cannot be configured separately

### ISSUE THREAD

**Issue by heldchen** [boxalino/plugin-magento2#11]
there seems currently no way to configure the Category view separately from the Search Result view - enabling the Filter and Left Facets on the Search config page will also enable them on the category view.

**Comment by tatsuya1** [comment]
This should only happen if the navigation is enabled.

**Comment by heldchen** [comment]
navigation is disabled.

**Comment by tatsuya1** [comment]
By enable on category view, you mean the slider or the whole filter?

**Comment by heldchen** [comment]
I'm not sure I follow. we do not want the boxalino filters & left facets to be loaded in the categories, yet they are and there seems to be no way to configure them separately from the SERP settings. this issue is related to the other issue #12 with the layout updates that are always applied.

currently, f.e. the bxSlider is always loaded on category classes because there's no separated configuration. this leads to exceptions when the category navigation is not what boxalino expects because the layout update is applied without checks as well.

**Comment by heldchen** [comment]
maybe it's a bit clearer now with the latest commits. in `catalog_category_view_type_layered.xml` you have:

```
<block class="Boxalino\Intelligence\Block\Facets" name="catalog.bxfilter.top"
   template="Boxalino_Intelligence::top_filters.phtml" before="-" 
   ifconfig="bxSearch/top_facet/enabled">
</block>
```

as we currently do not use the boxalino facets for navigating the categories, the `ifconfig` could look something like:

```
<block class="Boxalino\Intelligence\Block\Facets" name="catalog.bxfilter.top"
   template="Boxalino_Intelligence::top_filters.phtml" before="-" 
   ifconfig="bxCategories/top_facet/enabled">
</block>
```

**Comment by heldchen** [comment]
fixed in the latest commits, thanks!
