### ISSUE TITLE
Category filter is incorrectly rendered and ordered

### ISSUE THREAD

**Issue by heldchen** [boxalino/plugin-magento2#13]
![image](https://cloud.githubusercontent.com/assets/299636/17457633/0051c52e-5bfe-11e6-8706-99bfc6f9d272.png)

the order of the categories is not in the defined order (compare menu navigation vs layered navigation)

![image](https://cloud.githubusercontent.com/assets/299636/17457831/f1635460-5c02-11e6-8386-f8e5404aab34.png)
"Home" should be replaced with "All Categories" and put on the same level as the selected category ("Nager").

**Comment by heldchen** [comment]
the search now throws an exception after latest commits:

1 exception(s):
Exception #0 (Exception): Notice: Undefined index: Default Category in /srv/httpd/test/src/www/app/code/Boxalino/Intelligence/Model/Attribute.php on line 212

Exception #0 (Exception): Notice: Undefined index: Default Category in /srv/httpd/test/src/www/app/code/Boxalino/Intelligence/Model/Attribute.php on line 212
#0 /srv/httpd/test/src/www/app/code/Boxalino/Intelligence/Model/Attribute.php(212): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/srv/httpd/test...', 212, Array)
#1 /srv/httpd/test/src/www/app/code/Boxalino/Intelligence/Model/Attribute.php(107): Boxalino\Intelligence\Model\Attribute->_getItemsData()
#2 /srv/httpd/test/src/www/vendor/magento/module-catalog/Model/Layer/Filter/AbstractFilter.php(156): Boxalino\Intelligence\Model\Attribute->_initItems()
#3 /srv/httpd/test/src/www/vendor/magento/module-catalog/Model/Layer/Filter/AbstractFilter.php(145): Magento\Catalog\Model\Layer\Filter\AbstractFilter->getItems()
#4 /srv/httpd/test/src/www/vendor/magento/module-catalog/Model/Layer/Category/AvailabilityFlag.php(33): Magento\Catalog\Model\Layer\Filter\AbstractFilter->getItemsCount()
#5 /srv/httpd/test/src/www/vendor/magento/module-catalog/Model/Layer/Category/AvailabilityFlag.php(23): Magento\Catalog\Model\Layer\Category\AvailabilityFlag->canShowOptions(Array)
#6 /srv/httpd/test/src/www/vendor/magento/module-layered-navigation/Block/Navigation.php(107): Magento\Catalog\Model\Layer\Category\AvailabilityFlag->isEnabled(Object(Magento\Catalog\Model\Layer\Search\Interceptor), Array)
#7 /srv/httpd/test/src/www/app/code/Boxalino/Intelligence/view/frontend/templates/layer/view.phtml(14): Magento\LayeredNavigation\Block\Navigation->canShowBlock()
#8 /srv/httpd/test/src/www/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/srv/httpd/test...')
#9 /srv/httpd/test/src/www/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\LayeredNavigation\Block\Navigation), '/srv/httpd/test...', Array)
#10 /srv/httpd/test/src/www/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/srv/httpd/test...')
#11 /srv/httpd/test/src/www/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#12 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#13 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('catalogsearch.l...')
#14 /srv/httpd/test/src/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('catalogsearch.l...')
#15 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('catalogsearch.l...')
#16 /srv/httpd/test/src/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('catalogsearch.l...', true)
#17 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('catalogsearch.l...')
#18 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('sidebar.main')
#19 /srv/httpd/test/src/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('sidebar.main')
#20 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('sidebar.main')
#21 /srv/httpd/test/src/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('sidebar.main', true)
#22 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('sidebar.main')
#23 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('div.sidebar.mai...')
#24 /srv/httpd/test/src/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('div.sidebar.mai...')
#25 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('div.sidebar.mai...')
#26 /srv/httpd/test/src/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('div.sidebar.mai...', true)
#27 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('div.sidebar.mai...')
#28 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('columns')
#29 /srv/httpd/test/src/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('columns')
#30 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns')
#31 /srv/httpd/test/src/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('columns', true)
#32 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('columns')
#33 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.content')
#34 /srv/httpd/test/src/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#35 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content')
#36 /srv/httpd/test/src/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.content', true)
#37 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.content')
#38 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#39 /srv/httpd/test/src/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#40 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#41 /srv/httpd/test/src/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#42 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#43 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#44 /srv/httpd/test/src/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#45 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#46 /srv/httpd/test/src/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#47 /srv/httpd/test/src/www/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#48 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\View\Layout->getOutput()
#49 /srv/httpd/test/src/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(494): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#50 /srv/httpd/test/src/www/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#51 /srv/httpd/test/src/www/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#52 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#53 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#54 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-varnish-...')
#55 /srv/httpd/test/src/www/vendor/magento/module-page-cache/Model/Controller/Result/VarnishPlugin.php(74): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#56 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\Controller\Result\VarnishPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#57 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'renderResult', Object(Magento\Framework\View\Result\Page\Interceptor), Array, 'result-builtin-...')
#58 /srv/httpd/test/src/www/vendor/magento/module-page-cache/Model/Controller/Result/BuiltinPlugin.php(67): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#59 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\Controller\Result\BuiltinPlugin->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#60 /srv/httpd/test/src/www/var/generation/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#61 /srv/httpd/test/src/www/vendor/magento/framework/App/View.php(221): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#62 /srv/httpd/test/src/www/vendor/magento/module-catalog-search/Controller/Result/Index.php(91): Magento\Framework\App\View->renderLayout()
#63 /srv/httpd/test/src/www/app/code/Boxalino/Intelligence/Controller/IndexController.php(67): Magento\CatalogSearch\Controller\Result\Index->execute()
#64 /srv/httpd/test/src/www/var/generation/Boxalino/Intelligence/Controller/IndexController/Interceptor.php(24): Boxalino\Intelligence\Controller\IndexController->execute()
#65 /srv/httpd/test/src/www/vendor/magento/framework/App/Action/Action.php(102): Boxalino\Intelligence\Controller\IndexController\Interceptor->execute()
#66 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#67 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(70): Boxalino\Intelligence\Controller\IndexController\Interceptor->___callParent('dispatch', Array)
#68 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Boxalino\Intell...', 'dispatch', Object(Boxalino\Intelligence\Controller\IndexController\Interceptor), Array, 'contextPlugin')
#69 /srv/httpd/test/src/www/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#70 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Boxalino\Intelligence\Controller\IndexController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#71 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Boxalino\Intell...', 'dispatch', Object(Boxalino\Intelligence\Controller\IndexController\Interceptor), Array, 'customer-app-ac...')
#72 /srv/httpd/test/src/www/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#73 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Boxalino\Intelligence\Controller\IndexController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#74 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Boxalino\Intell...', 'dispatch', Object(Boxalino\Intelligence\Controller\IndexController\Interceptor), Array, 'storeCheck')
#75 /srv/httpd/test/src/www/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#76 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Boxalino\Intelligence\Controller\IndexController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#77 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Boxalino\Intell...', 'dispatch', Object(Boxalino\Intelligence\Controller\IndexController\Interceptor), Array, 'tax-app-action-...')
#78 /srv/httpd/test/src/www/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Boxalino\Intelligence\Controller\IndexController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#79 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Boxalino\Intelligence\Controller\IndexController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#80 /srv/httpd/test/src/www/var/generation/Boxalino/Intelligence/Controller/IndexController/Interceptor.php(39): Boxalino\Intelligence\Controller\IndexController\Interceptor->___callPlugins('dispatch', Array, Array)
#81 /srv/httpd/test/src/www/vendor/magento/framework/App/FrontController.php(55): Boxalino\Intelligence\Controller\IndexController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#82 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#83 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#84 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#85 /srv/httpd/test/src/www/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#86 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#87 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#88 /srv/httpd/test/src/www/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#89 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#90 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#91 /srv/httpd/test/src/www/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#92 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#93 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#94 /srv/httpd/test/src/www/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#95 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#96 /srv/httpd/test/src/www/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#97 /srv/httpd/test/src/www/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#98 /srv/httpd/test/src/www/vendor/magento/framework/Interception/Interceptor.php(146): Magento\Framework\App\Http->launch()
#99 /srv/httpd/test/src/www/var/generation/Magento/Framework/App/Http/Interceptor.php(26): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
#100 /srv/httpd/test/src/www/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#101 /srv/httpd/test/src/www/pub/index.php(42): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#102 {main}

**Comment by tatsuya1** [comment]
Just fixed it on the test server, will commit that fix this afternoon.

**Comment by heldchen** [comment]
fixed in latest commits, thanks!

**Comment by heldchen** [comment]
the latest commits reintroduced the category sorting problem:
![image](https://cloud.githubusercontent.com/assets/299636/17679307/2d1c88f2-633b-11e6-8019-f0485a621ee4.png)
