### ISSUE TITLE
Currently selected filter facets not shown in search

### ISSUE THREAD

**Issue by heldchen** [boxalino/plugin-magento2#18]
here's an example of a selected native magento layered navigation facet:

![image](https://cloud.githubusercontent.com/assets/299636/17457844/89b8ec48-5c03-11e6-8b1f-28eb32c069e4.png)

on the search result page, the selected facet (f.e. a brand) is missing above "Alles löschen". there is no visual indication that a brand has been selected on the search https://mysite.com/catalogsearch/result/index/?bx_products_brand=Hill%27s&q=futter

![image](https://cloud.githubusercontent.com/assets/299636/17457880/6aa1a6b4-5c04-11e6-8f56-6ed08def5d8d.png)

 additionally, "Alles löschen" should only appear if the user actually made a filter selection.

**Comment by tatsuya1** [comment]
should be fixed with the last commit.

**Comment by heldchen** [comment]
confirmed fixed in the latest commits, thanks!
