### ISSUE TITLE
A bxRecommendationBlock inside a cms block inside a cms page throws error

### ISSUE THREAD

**Issue by heldchen** [boxalino/plugin-magento2#19]
`Fehler beim Filtern der Vorlage: Notice: Trying to get property of non-object in /var/www/users/xyz/src/www/app/code/Boxalino/Intelligence/Lib/BxChooseResponse.php on line 55`

**Comment by tatsuya1** [comment]
Could you tell me which cms page it is?

**Comment by heldchen** [comment]
I added an example to https://domain/i-ueber-uns/ it uses the block from https://domain/c-pferde/

**Comment by heldchen** [comment]
confirmed as fixed in the latest commits
