### ISSUE TITLE
Search preview should be rate limited with old requests discared

### ISSUE THREAD

**Issue by heldchen** [boxalino/plugin-magento2#20]
![autosearch](https://cloud.githubusercontent.com/assets/299636/17462899/3fdfaf04-5cbb-11e6-8191-ce2658f89701.gif)

real time gif...

**Comment by tatsuya1** [comment]
Should be fixed with the latest commit.

**Comment by heldchen** [comment]
is that commit already pushed? the current github codebase still has this problem

**Comment by tatsuya1** [comment]
looks like it isn't pushed yet, I was told it was, will do it right away.

**Comment by heldchen** [comment]
something is not right... now the preview window has a huge delay:

![untitled screencast - edited](https://cloud.githubusercontent.com/assets/299636/17591949/9efad590-5fe0-11e6-945a-1ddc9a8d570d.gif)

**Comment by tatsuya1** [comment]
We have tested our autocomplete and came to the conclusion that the effective time spent in our code for the autocomplete is about 0.3 seconds. Now the 1.4 seconds after we return the json is managed by magento and we have no influence on that.

**Comment by heldchen** [comment]
much better now, closing for the moment. it is still slow, but seems to be on magento2's side.
