### ISSUE TITLE
CmsWidgetBlock referenced in etc/frontend/di.xml is missing

### ISSUE THREAD

**Issue by heldchen** [boxalino/plugin-magento2#21]
`<preference for="Magento\Cms\Block\Widget\Block" type="Boxalino\Intelligence\Block\CmsWidgetBlock" />
`
class does not exist in the repository

**Comment by tatsuya1** [comment]
That’s true, I forgot to commit those files yesterday. Will commit them this afternoon.

**Comment by heldchen** [comment]
obsolete with latest commits
