### ISSUE TITLE
Search: Selected Filters: "Back" link for Categories is broken

### ISSUE THREAD

**Issue by heldchen** [boxalino/plugin-magento2#22]
http://mysite.com/catalogsearch/result/index/?bx_category_id=8&q=futter

![image](https://cloud.githubusercontent.com/assets/299636/17524306/5b2f0cc4-5e5e-11e6-91e4-a54544b6017f.png)

-> click on "zurück"

```
1 exception(s):
Exception #0 (Exception): Notice: Trying to get property of non-object in /srv/httpd/test/src/www/app/code/Boxalino/Intelligence/Lib/BxChooseResponse.php on line 131

Exception #0 (Exception): Notice: Trying to get property of non-object in /srv/httpd/test/src/www/app/code/Boxalino/Intelligence/Lib/BxChooseResponse.php on line 131
```

what is the intent of the "Zurück" link anyway? it is obsolete as there's already the close button (X). can this be removed in a config setting or template override?

**Comment by tatsuya1** [comment]
Should be fixed now with the latest commit.

**Comment by heldchen** [comment]
confirmed as fixed, thanks alot!
