### ISSUE TITLE
Exception "Trying to get property of non-object" with some search strings

### ISSUE THREAD

**Issue by heldchen** [boxalino/plugin-magento2#23]
for example https://mysite.com/catalogsearch/result/?q=g-677

```
1 exception(s):
Exception #0 (Exception): Notice: Trying to get property of non-object in /srv/httpd/test/src/www/app/code/Boxalino/Intelligence/Lib/BxChooseResponse.php on line 131

Exception #0 (Exception): Notice: Trying to get property of non-object in /srv/httpd/test/src/www/app/code/Boxalino/Intelligence/Lib/BxChooseResponse.php on line 131
#0 /srv/httpd/test/src/www/app/code/Boxalino/Intelligence/Lib/BxChooseResponse.php(131): Magento\Framework\App\ErrorHandler->handler(8, 'Trying to get p...', '/srv/httpd/test...', 131, Array)
#1 /srv/httpd/test/src/www/app/code/Boxalino/Intelligence/Helper/P13n/Adapter.php(462): com\boxalino\bxclient\v1\BxChooseResponse->getFacets('search')
#2 /srv/httpd/test/src/www/app/code/Boxalino/Intelligence/Model/FilterList.php(78): Boxalino\Intelligence\Helper\P13n\Adapter->getFacets()
```

**Comment by tatsuya1** [comment]
Should be fixed with the latest commit.

**Comment by heldchen** [comment]
yep, can confirm the exception is fixed, but the result page looks weird:

![image](https://cloud.githubusercontent.com/assets/299636/17625389/f7c3a4a4-60a8-11e6-9d7f-40f1faad8f7c.png)

the real search string was "g-677"

**Comment by tatsuya1** [comment]
It's server side, we have to look at it on monday when sylvain is back.

**Comment by heldchen** [comment]
perfect, thanks! have a good weekend

**Comment by tatsuya1** [comment]
The conclusion with Sylvain was that it's server side. We will be fixing this issue asap. Please close this ticket, as it is not related to the plugin. If you would like to address this issue further, please write a ticket at: support@boxalino.com. Thank you.

**Comment by heldchen** [comment]
sure. please let me know when you had a chance to fix this server side.
