### ISSUE TITLE
selected Layered Navigation Filters are not rendered

### ISSUE THREAD

**Issue by heldchen** [boxalino/plugin-magento2#32]
url: `/catalogsearch/result/index/?bx_products_phase_of_life=Adult&bx_products_taste=Fisch&q=test`

![image](https://cloud.githubusercontent.com/assets/299636/17785759/52cc080e-6582-11e6-8dd8-b4073a16f750.png)

**Comment by tatsuya1** [comment]
all the filters were sent in the request, but we only display filters which return data in the response.

**Comment by heldchen** [comment]
i meant: the "Geschmack" attribute is set to "Fisch" but it is not shown that it is selected and you cannot unselect it.

this block is missing in the search results:
![image](https://cloud.githubusercontent.com/assets/299636/17802118/9acf7f8e-65ee-11e6-951f-b0fd6136cfcf.png)

**Comment by heldchen** [comment]
fixed in the latest commits, thanks
