### ISSUE TITLE
Subphrase page layout looks a bit weird

### ISSUE THREAD

**Issue by heldchen** [boxalino/plugin-magento2#37]
search query was `/catalogsearch/result/?q=welches+futter+ist+das+richige%3F`

![image](https://cloud.githubusercontent.com/assets/299636/17808918/317d225a-6613-11e6-8b20-938fffe4a518.png)

also shouldn't that only be shown if there are actually more than 1 subphrase?

**Comment by tatsuya1** [comment]
apparently not, I also assumed that subphrases only appear if there are more than 2 results, but I was told that's not the case.

**Comment by heldchen** [comment]
but in this case the subphrase is "exactly" what was searched for minus the extra "?" (which is also not shown in the first "search results:" title)...  anyway, nothing too serious.

**Comment by tatsuya1** [comment]
The system is detecting that the query is a subphrase, as such it is returned, but if only one of those queries has results it can happen that only this query is diplayed.

**Comment by heldchen** [comment]
ok, i understand. do you know of a search term that would result in two or more subphrases?

**Comment by heldchen** [comment]
by the way: in the old magento1 extension this exact same search term is handled much more gracefully, reduced to "futter". could it be that the 2nd title in the screenshot actually should say "futter"?

**Comment by heldchen** [comment]
fixed in latest commit, thanks!
